export default {
  API: {
    ENV: 'DEV',
    URL: 'http://localhost:4580'
  },
  ACCOUNT_HELP_LINK: 'http://www.anz.com/internet-banking/help/accounts/',
  CANCEL: 'Cancel',
  CONTINUE: 'Continue',
  SAVE: 'Save',
  DONE: 'Done',
  START: 'Start Again',
  CARD_IMP_INFO_1: 'Important information',
  CARD_IMP_INFO_2: 'All of your cards are displayed above',
  NO_CARDS: 'No cards match your search criteria',
  INELIGIBLE_CARDS: 'Ineligible card',
  NO_MATCHING_CARDS: 'No Matching Cards!!',
  PAYMENTS: 'Payments',
  PROFILE: 'Profile',
  APPLY: 'Apply',
  FEEDBACK: 'Feedback',
  IB_URL_DOMAIN: 'http://appau301mel5125.globaltest.anz.com:9080/IBAU/BANKAWAYTRAN;jsessionid=0000',
  IB_URL_HOME_SFX: ':-1?fromReactApp=home',
  IB_URL_PROFILE_SFX: ':-1?fromReactApp=profile',
  IB_URL_PAYMENT_SFX: ':-1?fromReactApp=payments',
  IB_URL_APPLY_SFX: ':-1?fromReactApp=apply',
  IB_URL_FEEDBACK: '#/feedbackpage',
  IB_FEEDBACK_APPLY_LINK: 'https://yoursay.anz.com/c/a/5bprhiSvFtc2bSwrIC7pkr',
  IB_URL_LOGOUT_SFX: ':-1?fromReactApp=logout',
  IB_URL_MAIL_SFX: ':-1?fromReactApp=mail',
  IB_URL_CONTACTUS_SFX: ':-1?fromReactApp=contact',
  IB_URL_HOME: '',
  IB_URL_PROFILE: '',
  IB_URL_PAYMENT: '',
  IB_URL_APPLY: '',
  IB_URL_LOGOUT: '',
  IB_URL_MAIL: '',
  IB_URL_CONTACTUS: '',
  PEP_URL: 'http://10.186.165.52/PepHandlerTest/api/handler/ib/bff',
  CARD_SERVICE_SFX: '/ib/bff/cards/getCardList',
  USER_INFO_SFX: '/ib/bff/user/contact',
  MANAGE_PIN_HEADER: 'Manage your card PIN',
  jSessionId: '',
  SEND_NEW_CODE: 'Send a new code to try again',
  PIN_CHANGE_INFO_1: 'To ensure your change of PIN for card ending in',
  PIN_CHANGE_INFO_2: ', we will send a verification code to your mobile number',
  SEND_SMS_CODE: 'Send me a SMS code',
  VERIFY_PIN: 'Verify your change of PIN',
  PAGE_FOOTER_TEXT_1: 'Update your mobile number',
  PAGE_FOOTER_TEXT_2: 'Need help? Call ANZ on 13 33 50(+61 3 9683 8833 from overseas)',
  NO_CARDS_ELIGIBLE: 'None of your cards are eligible for card management',
  SELECT_ELIGIBLE_CARD: 'Select an eligible card below',
  OTP_MISMATCH_ERROR: '',
  MANAGEPIN_4PIN: 'Enter a new 4 digit card PIN',
  MANAGEPIN_CONFIRMPIN: 'Confirm your new card PIN',
  MANAGEPIN_SUGGESTION: 'Dont choose a PIN that can be easily guessed',
  MANAGEPIN_SUGGESTION_EX: '(eg: Your birthday or name)',
  MANAGEPIN_MISMATCH: 'The PIN entered need to match',
  SUCCESSFUL_PIN_CHANGE: 'Your card\'s PIN has been successfuly changed',
  CHANGES_TO_CARD: 'Changes to card linked to:',
  FEEDBACK_ACK_INFO: 'You`re invite you to join our online research panel where we`ll occasionally send you emails to take part in online surveys.',
  FEEDBACK_ACK: 'Thanks for the feedback!',
  FEEDBACK_FORM: 'Rate your ANZ Internet Banking experience',
  FEEDBACK_FORM_RATE: 'Choose a star to rate',
  FEEDBACK_COMMENTS_PLACEHOLDER: 'For your security,please do not provide any personal account  information.',
  FEEDBACK_ERROR: 'An error occured',
  FEEDBACK_ERROR_INFO: 'Unfortunately our service is temporarily unavailable. We apologise for the inconvenience.',
  TAPCALL_INFO: 'Need a response?',
  FEEDBACK_COMMENTS: 'Comments',
  LOADER_MSG: 'Submitting your feedback',
  FEEDBACK_TITLE: 'Feedback',
  COMMENTS_HEADING: 'Want to tell us more?',
  COMMENTS_HEADING_ID: 'feedbackComments',
  SECUREMAIL: 'Securemail',
  FEEDBACK_FORM_CANCEL: 'Cancel',
  FEEDBACK_FORM_SUBMIT: 'Submit',
  TAP_CALL_TEXT1: 'Call ',
  TAP_CALL_NO: '13 13 44 ',
  TAP_CALL_TEXT2: 'or send us a ',
  WARNING_ICON: 'Warning',
  MODAL_TITLE: 'feedbackModal',
  MODAL_REF: 'modalCmp',
  MODAL_ROLE: 'dialog',
  MODAL_CLOSE_ICON: 'Cross',
  FEEDBACK_CHAT: 'Feedback Chat',
  STAR_SELECT_ICON: 'Rating Star Selected',
  STAR_SELECT_ID: 'starrateselect',
  STAR_UNSELECT_ICON: 'Rating Star Unselected',
  STAR_UNSELECT_ID: 'starrate',
  FEEDBACK_FORM_ACK_BUTTON: 'No thanks',
  FEEDBACK_FORM_APPLY: 'Apply',
  CHECK_ICON: 'Check',
  RESPONSE_STATUS: 200,
  BROWSERNAME_FIREFOX: 'Firefox',
  BROWSERNAME_SAFARI: 'Safari',
  BROWSERNAME_CHROME: 'Chrome',
  BROWSERNAME_MSIE1: 'Microsoft Internet Explorer',
  BROWSERNAME_MSIE2: 'MSIE',
  BROWSERNAME_OPERA: 'Opera',
  VERSION: 'Version',
  DEVICE_TYPE_DESK: 'Desktop',
  DEVICE_TYPE_TAB: 'Tablet',
  DEVICE_TYPE_MOB: 'Mobile',
  OSNAME: 'unknown',
  OSNAME_WIN: 'Windows',
  OSNAME_WIN1: 'Win',
  OSNAME_MAC: 'MacOS',
  OSNAME_MAC1: 'Mac',
  OSNAME_X11: 'X11',
  OSNAME_X12: 'UNcodeLen',
  OSNAME_LINUX: 'Linux',
  CLOSE: 'Close',
  TEXT_AREA: 'textArea',
  ACCORD_BEFORE_CLS: 'beforeshowcls',
  ACCORD_SHOW_CLS: 'showcls',
  ACCORD_HIDE_CLS: 'hidecls',
  ARROW_UP_ICON: 'Arrow Up',
  ARROW_DOWN_ICON: 'Arrow Down'
}
